import fs from "node:fs";
import path from "node:path";
import { getOutputsDir, getRepoRoot, getUploadsDir } from "./python";

export interface StorageStats {
  uploadsBytes: number;
  uploadsCount: number;
  outputsBytes: number;
  outputsCount: number;
  totalBytes: number;
  totalFiles: number;
}

export interface CleanResult {
  deletedFiles: number;
  freedBytes: number;
  errors: string[];
}

export interface CleanOptions {
  maxAgeMs?: number; // 0 = remove all temporary files, > 0 = only remove files older than maxAgeMs
  cleanUploads?: boolean;
  cleanOutputs?: boolean;
}

// Patterns of temporary output files generated by the web UI and TTS/split pipelines
const TEMP_OUTPUT_PATTERNS = [
  /^web_output_/i,
  /^tts_output_/i,
  /^tts_rvc_output_/i,
  /^split_/i,
  /^tts_input_/i,
];

function isTempOutputFile(filename: string): boolean {
  return TEMP_OUTPUT_PATTERNS.some((p) => p.test(filename));
}

export function getStorageStats(): StorageStats {
  let uploadsBytes = 0;
  let uploadsCount = 0;
  let outputsBytes = 0;
  let outputsCount = 0;

  const uploadsDir = getUploadsDir();
  if (fs.existsSync(uploadsDir)) {
    try {
      const files = fs.readdirSync(uploadsDir);
      for (const file of files) {
        if (file === ".gitkeep") continue;
        const fullPath = path.join(uploadsDir, file);
        try {
          const stat = fs.statSync(fullPath);
          if (stat.isFile()) {
            uploadsBytes += stat.size;
            uploadsCount += 1;
          }
        } catch {
          /* ignore unreadable */
        }
      }
    } catch {
      /* ignore */
    }
  }

  const outputsDir = getOutputsDir();
  if (fs.existsSync(outputsDir)) {
    try {
      const files = fs.readdirSync(outputsDir);
      for (const file of files) {
        if (file === ".gitkeep" || file === "_uploads" || file === "audio-others") continue;
        if (!isTempOutputFile(file)) continue;
        const fullPath = path.join(outputsDir, file);
        try {
          const stat = fs.statSync(fullPath);
          if (stat.isFile()) {
            outputsBytes += stat.size;
            outputsCount += 1;
          }
        } catch {
          /* ignore unreadable */
        }
      }
    } catch {
      /* ignore */
    }
  }

  return {
    uploadsBytes,
    uploadsCount,
    outputsBytes,
    outputsCount,
    totalBytes: uploadsBytes + outputsBytes,
    totalFiles: uploadsCount + outputsCount,
  };
}

export function cleanStorage(options: CleanOptions = {}): CleanResult {
  const { maxAgeMs = 0, cleanUploads = true, cleanOutputs = true } = options;
  const now = Date.now();
  let deletedFiles = 0;
  let freedBytes = 0;
  const errors: string[] = [];

  if (cleanUploads) {
    const uploadsDir = getUploadsDir();
    if (fs.existsSync(uploadsDir)) {
      try {
        const files = fs.readdirSync(uploadsDir);
        for (const file of files) {
          if (file === ".gitkeep") continue;
          const fullPath = path.join(uploadsDir, file);
          try {
            const stat = fs.statSync(fullPath);
            if (!stat.isFile()) continue;
            if (maxAgeMs > 0 && now - stat.mtimeMs < maxAgeMs) continue;
            fs.unlinkSync(fullPath);
            deletedFiles += 1;
            freedBytes += stat.size;
          } catch (e) {
            errors.push(`Failed to remove ${file}: ${String(e)}`);
          }
        }
      } catch (e) {
        errors.push(`Failed to scan uploads dir: ${String(e)}`);
      }
    }
  }

  if (cleanOutputs) {
    const outputsDir = getOutputsDir();
    if (fs.existsSync(outputsDir)) {
      try {
        const files = fs.readdirSync(outputsDir);
        for (const file of files) {
          if (file === ".gitkeep" || file === "_uploads" || file === "audio-others") continue;
          if (!isTempOutputFile(file)) continue;
          const fullPath = path.join(outputsDir, file);
          try {
            const stat = fs.statSync(fullPath);
            if (!stat.isFile()) continue;
            if (maxAgeMs > 0 && now - stat.mtimeMs < maxAgeMs) continue;
            fs.unlinkSync(fullPath);
            deletedFiles += 1;
            freedBytes += stat.size;
          } catch (e) {
            errors.push(`Failed to remove ${file}: ${String(e)}`);
          }
        }
      } catch (e) {
        errors.push(`Failed to scan outputs dir: ${String(e)}`);
      }
    }
  }

  // Clean any stale PID files or temp text files in assets
  try {
    const repoRoot = getRepoRoot();
    const pidFiles = ["infer_pid.txt", "extract_pid.txt"];
    for (const pidFile of pidFiles) {
      const p = path.join(repoRoot, "assets", pidFile);
      if (fs.existsSync(p)) {
        try {
          fs.unlinkSync(p);
        } catch {
          /* ignore */
        }
      }
    }
  } catch {
    /* ignore */
  }

  return { deletedFiles, freedBytes, errors };
}

let cleanerInterval: NodeJS.Timeout | null = null;

// Starts the automatic background storage cleaner: runs once on boot (after 15s delay)
// and then periodically every intervalMs (default: 6 hours), removing temporary files
// older than maxAgeMs (default: 24 hours).
export function startStorageCleaner(intervalMs = 6 * 3600 * 1000, maxAgeMs = 24 * 3600 * 1000) {
  if (cleanerInterval) return;

  const runCleanup = () => {
    try {
      const res = cleanStorage({ maxAgeMs, cleanUploads: true, cleanOutputs: true });
      if (res.deletedFiles > 0) {
        const mb = (res.freedBytes / (1024 * 1024)).toFixed(2);
        // eslint-disable-next-line no-console
        console.log(`[storage-cleaner] Cleaned ${res.deletedFiles} temporary files (${mb} MB freed)`);
      }
    } catch {
      /* ignore */
    }
  };

  // Delayed initial run so startup latency is unaffected
  const initialTimer = setTimeout(runCleanup, 15000);
  initialTimer.unref();

  cleanerInterval = setInterval(runCleanup, intervalMs);
  cleanerInterval.unref();
}
